export default [
  {
    type: 'Side Project',
    image: './images/thissite.jpg',
    title: 'This Site',
    technologies: ['React', 'Material-UI', 'Node Express'],
    link: 'https://github.com/Daniel-Davies/PortfolioSite.git',
    description: 'A website from scratch to showcase my recent projects jobs',
    gif: './images/thissite.gif',
  },
  {
    type: 'Job',
    image: './images/lynch.jpg',
    title: 'Merrill Lynch',
    description: 'Worked mainly in React and Perspective (with complimentary frameworks Material-UI and Redux) to build an analytics tool for Equity Risk data. Also built a Python Flask backend to interface with a KDB/Q Data Store',
    technologies: ['React', 'Redux', 'Material-UI', 'finos/Perspective', 'Flask', 'KDB/Q'],
  },
  {
    type: 'Research',
    image: './images/brencs.jpg',
    title: 'UCI Dept. of CS',
    link: 'https://github.com/Daniel-Davies/ResearchProject',
    description: "Data Analytics research project that tried to uncover the reasons behind the ever rising number of 'frequent flyer' patients in US hospitals, through use of Machine Learning on a large dataset",
    technologies: ['Python', 'Matplotlib', 'SKLearn', 'Numpy/SciPy', 'Jupyter Notebook'],
  },
  {
    type: 'Job',
    image: './images/portal.PNG',
    gif: './images/cove.gif',
    title: "UCI Applied Innovation ('The Cove')",
    description: 'Worked as a paid full stack developer for UC Irvine to build an online portal to enable intuitive searching of faculty for University Partners. Main part of my time focussed on building a search engine module in C#',
    technologies: ['C#', 'ASP.NET Core', 'MySQL', 'SQL Server', 'Bootstrap', 'Razor'],
  },
  {
    type: 'Hackathon',
    image: './images/hacksc.jpg',
    link: 'https://devpost.com/software/align-f4o103',
    title: 'HackSC 2019 Winner (USC)',
    gif: './images/hacksc.gif',
    description: "Won Best Web/Mobile app at USC's annual hackathon for an app that connected people suffering with similar diseases such as MS onto a platform that would let them find support from people in a similar situation",
    technologies: ['React', 'React Native', 'AWS Cloud 9', 'AWS S3', 'AWS Cognito'],
  },
  {
    type: 'Hackathon',
    image: './images/treehacks.jpg',
    gif: './images/stanford.gif',
    link: 'https://devpost.com/software/treehacks-pejm73',
    title: 'TreeHacks 2019 Winner (Stanford University)',
    description: 'Won category of Most Creative App for a machine learning project that focussed on identifying whether a patient had a viral or bacterial infection based on GEO2R samples (collection from blood sample of patient etc)',
    technologies: ['Django', 'Bootstrap', 'SKLearn', 'Highcharts'],
  },
  {
    type: 'Hackathon',
    image: './images/philan.PNG',
    link: 'https://devpost.com/software/philanthropoints',
    title: 'SLOHacks 2019 Winner (Cal Poly SLO)',
    gif: './images/calpoly.gif',
    technologies: ['Flask', 'Bootstrap'],
    description: 'Build a platform available for Web and IOS that leveraged company sponsorship connections to promote volunteering in the local community. Won Best Hack for Social Good, and Best Use of Hathway Corporate Connections',
  },
  {
    type: 'Team Project',
    link: 'https://github.com/Daniel-Davies/13-RoboFarm',
    image: './images/robofarm.PNG',
    title: 'RoboFarm- Microsoft Malmo AI Project',
    description: 'Microsoft Malmo provides an API over the popular game minecraft to leverage a gaming environment for training AI/ML algorithms. We used a genetic algorithm in the game to optimse planting locations for wheat seeds.',
    technologies: ['Malmo', 'Python'],
  },
  {
    type: 'Job',
    image: './images/socgen.jpg',
    title: 'SG Markets- Trade Execution Platform',
    description: "Formed part of the Exection Platform demo team. Built a demo version of a sales-trader platform, in a hackathon style, to demo to senior members of the bank. Also worked intensely with newer technolgies at the bank such as Chatbots connected to trader's desks, and machine learning on trading data.",
    technologies: ['Flask', 'Bootstrap', 'SKLearn'],
  },
  {
    type: 'Team Project',
    image: './images/bristol.jpg',
    link: 'https://github.com/Daniel-Davies/Bristol-Surplus-Food',
    title: 'Bristol Surplus Food',
    description: 'Formed part of a team that made a website for a charity in Bristol that helps connect supermarkets with surplus food to those in need of food, such as struggling families and the homeless',
    technologies: ['Java', 'Java Play', 'Bootstrap'],
  },
  {
    type: 'Hackathon',
    image: './images/hex.jpg',
    link: 'https://devpost.com/software/angryfacesinblockchain',
    title: 'Hex Hack 2018 Winner',
    description: 'I was on the winning team for an innovative application that first captures any security events using a camera, classifies the event as a security threat, then adds any threats to a global blockchain that can be used to track global threat alerts',
    technologies: ['Ethereum Library', 'Bootstrap', 'Azure cloud services', 'OpenCV'],
  },
  {
    type: 'Hackathon',
    image: './images/oxford.png',
    link: 'https://github.com/cjdudley1/ACDC.git',
    title: 'OxHack 2017 Winner- University of Oxford',
    description: "I was on the winning team for University of Oxford's hackathon, in which we built an app for the healthcare industry to use a webcam to monitor a patient's emotions, and on signal of any of any discomfort or pain, would trigger an email to alert a doctor.",
    technologies: ['Flask', 'Microsoft Cognitive Services'],
  },
  {
    type: 'Research',
    image: './images/cardiffUni.jpg',
    title: 'Cardiff University dept. of Physics',
    description: "I completed a research project at Cardiff University investigating the use of the earth's magnetic field as a replacement/ aid to the electromagnets used in MRI scannr's at hospitals ",
    technologies: ['Matlab'],
  },
];
